# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7e49346a78ae9aa082209e5f826156caacceaca43e09ae08bba81a6216f7fe5ddb48ea924dd3a8e0a012d9ab9be233b3e60c7be59f440c059eff9927d48f4a74

test:
  secret_key_base: 3c7db692a354ff5b367ff42e6955ae7f3c5a4808879f3928358303c81dfcc27ea19fcfae71c700fc540b54355536b7049634bd014e31ddb104df12f072864eca

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
